name: vv-festim-report-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python
  - jupyter-book
  - numpy
  - matplotlib
  - sphinx
  - sympy
  - fenics
  - numpy=1.24
  - ipython=8.24
  - pip
  - pip:
    - festim