name: vv-festim-report-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python
  - jupyter-book
  - jupytext # necessary to open MyST files using BinderHub https://jupyterbook.org/en/stable/interactive/launchbuttons.html#launchbuttons-binder
  - sphinx-tags
  - numpy
  - matplotlib
  - sphinx
  - sympy
  - pandas
  - fenics
  - numpy=1.24
  - ipython=8.23
  - gxx  # TODO after this is fixed https://github.com/conda-forge/fenics-feedstock/issues/204
  - pip
  - pip:
    - festim