name: vv-festim-report-env-festim-2

channels:
  - conda-forge
  - defaults

dependencies:
  - python
  - jupyter-book
  - jupytext # necessary to open MyST files using BinderHub https://jupyterbook.org/en/stable/interactive/launchbuttons.html#launchbuttons-binder
  - sphinx-tags
  - pyvista
  - numpy
  - matplotlib
  - sphinx
  - sympy
  - pandas
  - mpich
  - ipython=8.23
  - scipy
  - plotly
  - festim=2.0a2
  - pip
  - pip:
    - h_transport_materials
